version: '3.4'
services:
  golang:
     build:
       context: "."
       dockerfile: "build/docker/Dockerfile"
     container_name: golang
     env_file:
       - .env
     links:
       - redis
     depends_on:
       - "mysql"
       - "redis"
     restart: unless-stopped
     ports:
       - 8080:8080
  redis:
    image: redis:alpine
    container_name: redis
    depends_on:
      - mysql      
    ports:
      - 6380:6379
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_DATABASE: Library
      MYSQL_ROOT_PASSWORD: abc123
    ports:
      - 3307:3306
  json-server:
    image: vimagick/json-server
    command: -H 0.0.0.0 -p 3000 -w /build/docker/json-server/db.json
    ports:
      - 3000:3000
    volumes:
      - ./build/docker/json-server:/build/docker/json-server