version: '3.7'

services:
  account-service:
    build:
      context: ".."
      dockerfile: "docker/images/go/Dockerfile"
    container_name: account-service
    networks:
      - lib-net
    env_file:
      - ../.env
    depends_on:
      - "account-service-db-host"
    restart: unless-stopped
    working_dir: "/go/src/github.com/FelipeAz/golibcontrol/cmd/account/"
    expose:
      - 8082
    command: bash -c "CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main . && ./main"
    ports:
      - "8082:8082"
  account-service-db-host:
    image: mysql:8.0
    container_name: account-service-database
    networks:
      - lib-net
    environment:
      MYSQL_DATABASE: LibraryAccount
      MYSQL_ROOT_PASSWORD: abc123
      MYSQL_TCP_PORT: 3308
    ports:
      - "3308:3307"
networks:
  lib-net:
    external: true