version: '3.7'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    networks:
      - lib-net
  kafka:
    image: confluentinc/cp-kafka:latest
    networks:
      - lib-net
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    networks:
      - lib-net
    depends_on:
      - kafka
    ports:
      - "19000:9000"
networks:
  lib-net:
    external: true