// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: student.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GetStudentInfoClient is the client API for GetStudentInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GetStudentInfoClient interface {
	GetStudentInfo(ctx context.Context, in *GetStudentRequest, opts ...grpc.CallOption) (*GetStudentResponse, error)
}

type getStudentInfoClient struct {
	cc grpc.ClientConnInterface
}

func NewGetStudentInfoClient(cc grpc.ClientConnInterface) GetStudentInfoClient {
	return &getStudentInfoClient{cc}
}

func (c *getStudentInfoClient) GetStudentInfo(ctx context.Context, in *GetStudentRequest, opts ...grpc.CallOption) (*GetStudentResponse, error) {
	out := new(GetStudentResponse)
	err := c.cc.Invoke(ctx, "/GetStudentInfo/GetStudentInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GetStudentInfoServer is the server API for GetStudentInfo service.
// All implementations must embed UnimplementedGetStudentInfoServer
// for forward compatibility
type GetStudentInfoServer interface {
	GetStudentInfo(context.Context, *GetStudentRequest) (*GetStudentResponse, error)
}

// UnimplementedGetStudentInfoServer must be embedded to have forward compatible implementations.
type UnimplementedGetStudentInfoServer struct {
}

func (UnimplementedGetStudentInfoServer) GetStudentInfo(context.Context, *GetStudentRequest) (*GetStudentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStudentInfo not implemented")
}
func (UnimplementedGetStudentInfoServer) mustEmbedUnimplementedGetStudentInfoServer() {}

// UnsafeGetStudentInfoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GetStudentInfoServer will
// result in compilation errors.
type UnsafeGetStudentInfoServer interface {
	mustEmbedUnimplementedGetStudentInfoServer()
}

func RegisterGetStudentInfoServer(s grpc.ServiceRegistrar, srv GetStudentInfoServer) {
	s.RegisterService(&GetStudentInfo_ServiceDesc, srv)
}

func _GetStudentInfo_GetStudentInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStudentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GetStudentInfoServer).GetStudentInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/GetStudentInfo/GetStudentInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GetStudentInfoServer).GetStudentInfo(ctx, req.(*GetStudentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GetStudentInfo_ServiceDesc is the grpc.ServiceDesc for GetStudentInfo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GetStudentInfo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "GetStudentInfo",
	HandlerType: (*GetStudentInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStudentInfo",
			Handler:    _GetStudentInfo_GetStudentInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "student.proto",
}
